name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run pytest
      run: pytest -v > test_results.txt

    - name: Display scores
      run: |
        echo "Scores for each function:"
        cat test_results.txt
