name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install numpy
          pip install torch

      - name: Run tests
        run: |
         pytest -v > test_results.txt || echo "Tests failed"

      - name: Display scores
        run: |
          echo "Scores for each function:"
          cat test_results.txt
